### ISSUE TITLE
very cool... widgetize?

### ISSUE THREAD

**Issue by aztlan2k** [AdrianSchneider/jsonfui#2]
Hey @AdrianSchneider, very cool.  nice job.  Any chance this can be widget-ized and maybe included in blessed-contrib?   (_maybe it's already possible, just found your project and haven't actually looked at the code yet_)

It would be nice to be able to make it available as a widget that can be bundled with lists, tables, boxes, etc...

**Comment by AdrianSchneider** [comment]
Sorry for the super late reply... I'm not quite sure how I would componentize this. If you can give a little more direction on which parts would be useful, I'd be happy to give it some more thought.
