### ISSUE TITLE
Piping into docker container fails with "the input device is not a TTY"

### ISSUE THREAD

**Issue by Nevon** [AdrianSchneider/jsonfui#5]
When running jsonfui in a Docker container and piping the json into it, it fails to start with an error:

```
λ ~/workspace/jsonfui/ master* docker build --rm .
Sending build context to Docker daemon 6.144 kB
Step 1/4 : FROM mhart/alpine-node:latest
latest: Pulling from mhart/alpine-node
627beaf3eaaf: Pull complete
8967246b7a43: Pull complete
Digest: sha256:03f5cfca0497c84e7b5698e96bd757e388a352ad8ac8d940f88a2575840d04b8
Status: Downloaded newer image for mhart/alpine-node:latest
 ---> 4c526da8fee7
Step 2/4 : ENV JSONFUI_VERSION 1.2.4
 ---> Running in 0b1613ca0a45
 ---> 7312e2c2ce3b
Removing intermediate container 0b1613ca0a45
Step 3/4 : RUN npm install -g jsonfui@$JSONFUI_VERSION
 ---> Running in 50c6e101344b
/usr/bin/jsonfui -> /usr/lib/node_modules/jsonfui/bin/jsonfui
/usr/lib
`-- jsonfui@1.2.4
  +-- blessed@0.1.81
  +-- commander@2.9.0
  | `-- graceful-readlink@1.0.1
  `-- ttys@0.0.3

 ---> da139d831523
Removing intermediate container 50c6e101344b
Step 4/4 : ENTRYPOINT jsonfui
 ---> Running in 4a90af982bd3
 ---> 6203047c9a70
Removing intermediate container 4a90af982bd3
Successfully built 6203047c9a70
λ ~/ cat ~/Desktop/test.json | docker run -it -e $TERM 6203047c9a70
the input device is not a TTY
```

Mounting the json file and passing the path as a parameter works as expected:

```
λ ~/workspace/jsonfui/ master* docker run -it -v /Users/tommy.brunn/Desktop/test.json:/test.json 6203047c9a70 test.json
```

My reason for doing this is that I have a lot of colleagues who do not want to install node locally, and will definitely not keep it up to date, so running it in a Docker container would be very convenient for them (although copying wouldn't work).

My Dockerfile:

```
FROM mhart/alpine-node:latest

ENV JSONFUI_VERSION 1.2.4

RUN npm install -g jsonfui@$JSONFUI_VERSION

ENTRYPOINT ["jsonfui"]
```

**Comment by AdrianSchneider** [comment]
I spent an hour screwing around with this and reached a similar conclusion... although I got your specific use case working, I found another that doesn't.

```
# make an alias
# read stdin to a temp file, mount it, and call jsonfui with that temp file
alias jsonfui="cat - > /tmp/json; docker run -it -v /tmp/json:/json.json jsonfui /json.json"

# works
cat package.json | jsonfui

# does not work 
jsonfui < package.json
```

Being able to read from stdin and consume a file, then switch to interactive mode was a total hack that the `ttys` library helps with.

As another option, you may want to try using [nexe](https://github.com/nexe/nexe) to wrap the package in a binary and just run it directly.

**Comment by AdrianSchneider** [comment]
Even better, I got it working with the `pkg` tool, and have attached binaries for you:

https://github.com/AdrianSchneider/jsonfui/releases/tag/1.2.6

**Comment by AdrianSchneider** [comment]
I don't think using docker that way will be possible, but the binaries is a better solution to your original problem anyway.

**Comment by Nevon** [comment]
Thanks for the binaries!
